version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-yarn
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn ng build --prod
      - run:
          name: test
          command: yarn ng test --no-watch --no-progress
